### ISSUE TITLE
Questions about FPGA source code

### ISSUE THREAD

**Issue by myxingchao** [gregdavill/GlassUnicorn#2]
After reading your project, I am very interested, I don't know how to get the FPGA source code.

**Comment by greigs** [comment]
Some might be here, by the looks of it.. I'm still waiting on my FPGA to try it.
https://github.com/gregdavill/ice40-playground/tree/GlassUnicorn_24x24/projects/rgb_panel

**Comment by myxingchao** [comment]
Thank you for your reply, I am looking at the file is not found in the schematic of the control panel, I want to understand the principle to modify, maybe I can use ARM to try to develop

**Comment by greigs** [comment]
This isn't schematic code. It is the FPGA code.
https://github.com/gregdavill/ice40-playground/tree/GlassUnicorn_24x24/projects/rgb_panel/rtl

**Comment by gregdavill** [comment]
The panels are driven by an FPGA on the controller PCB. It's based on the rgb_panel code from here: https://github.com/smunaut/ice40-playground

This in turn is controlling the LEDs using Binary Coded Modulation. Here is a very detailed video on how this modulation scheme works. https://www.youtube.com/watch?v=Sq8SxVDO5wE

You should be able to develop similar code on an ARM if you wish.

**Comment by gregdavill** [comment]
Here is another good video explaining how to drive panels similar to mine. Which would be a good starting point if you want to write your own. https://www.youtube.com/watch?v=6iHTbGsnI8Q
